services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: preventx-backend
    ports:
      - "8000:8000"
    volumes:
      - protectx-db:/app/data
    environment:
      - VITE_ALLOWED_ORIGINS=http://localhost:8080,http://localhost:8081,http://localhost:80
      - DATABASE_URL=sqlite:///./data/sql_app.db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=/
    container_name: preventx-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always

volumes:
  protectx-db:
